### ISSUE TITLE
Use of covariates

### ISSUE THREAD

**Issue by antgomo** [statOmics/satuRn#14]
I see that the contrasts are built using limma, so i guees that the package could deal with covariates (age, gender, batch) using the typical limma approaches, am I correct?

Thanks

**Comment by jgilis** [comment]
Hello @antgomo,

That is correct. In the same way as limma/edgeR/DESeq2/... , `satuRn` builds upon a generalized linear modelling framework, so the specification of the design and contrasts can be done in the same way as for these methods.

If the design is complex, setting up the contrasts and interpreting the coefficients can still be non-trivial; you could check the closed issue https://github.com/statOmics/satuRn/issues/10 for an example. If something would still be unclear, feel free to reach out to me!

Jeroen
