### ISSUE TITLE
Is it compatible with 10X? Could it work with Seurat object? Should I use alevin/alevin-fry?

### ISSUE THREAD

**Issue by Romeo1-1** [statOmics/satuRn#22]
Hello, thank your for this very interesting package !

I have a practical question. I'm new to the Single Cell world and I would like to use your package on my dataset (Chromium 10X scRNAseq), consisting of 2 samples from the same patient, before and after treatment (at diagnosis/relapse).

Unfortunately, I haven't been able to make it work on my dataset. I tried to directly convert my SeuratObject to SingleCell then SummarizedExperiment but my rownames are my cellbarcodes, not my transcripts. I've been able to gather the spliced/unspliced information using velocyto, but I don't know how to integrate it. Alternatively, I saw that I could use alevin or alevin-fry to gather data, but before starting lengthy analyses I wanted your advice. 

Is it compatible with 10X data ? Could it work directly with Seurat object/velocyto ? Should I go back and use alevin/alevin-fry on my FASTQ files to then use your package ?

Thank you a lot in advance

**Comment by jgilis** [comment]
Hi Remi,

I haven't worked with *velocyto* yet. How does the count matrix look like? I understand the rows are cells (barcodes, demultiplexed) and the columns are features? But what are the features exactly? They are probably not transcripts or exons, right?

**Comment by jgilis** [comment]
Hi Remi,

I'm going to close this issue due to 2 months of inactivity. If you still have questions, feel free to reopen the issue!
