### ISSUE TITLE
Preprocessing killed

### ISSUE THREAD

**Issue by TolgaDuz** [statOmics/satuRn#30]
Hi Jeroen,

thanks for your wonderful tool!
I havent faced any issues up until now. It is not directly connect to your tool, rather than to the preprocessing part before.
Currently I create the countmatrix through the TPM columns from the quant.sf files which I get after quasi mapping with salmon. Attached is my script. But now I am working with a big dataset, with several 100 of cells and the merging process gets always killed. Do you have an efficient way to create the count matrix? I have access to an sungrid cluster, but even submitting to the cluster kills my job. Do you maybe have an efficient way/script which you can provide?
Thanks!

My current script:
[sal_merge_fancy.txt](https://github.com/statOmics/satuRn/files/12266614/sal_merge_fancy.txt)

Best,
Tolga

**Comment by TolgaDuz** [comment]
could solve it by concatenating the dataframes :)

**Comment by jgilis** [comment]
Hi @TdzBAS,

Do you mean your issue is resolved now and I can close it?

Jeroen

**Comment by TolgaDuz** [comment]
Hi @jgilis ,

yes, sorry for the circumstances.
Best
Tolga

**Comment by jgilis** [comment]
No worries at all, I am happy you found a solution.
I will close the issue!
