### ISSUE TITLE
Recommendation for large.n in filterByExpr

### ISSUE THREAD

**Issue by TolgaDuz** [statOmics/satuRn#31]
Hi @jgilis,

I have a single cell dataset with two groups of cell types, where each group comprises 900 cells. I am confused what to set for large.n in the filterByExpr function. I couldnt understand the documentation. May you help me here? The other parameters I set according to your recommendation from the paper for a single cell dataset.

![image](https://github.com/statOmics/satuRn/assets/91309592/af66aa96-02f1-48c6-af69-996d271802e9)

Best,
Tolga

**Comment by jgilis** [comment]
Hi @TdzBAS,

This is a question for the edgeR people, you can easily reach them through the BioConductor forum https://support.bioconductor.org/. If you just post this question with the edgeR tag I expect replies to come in very quickly.

Best regards,

Jeroen
