### ISSUE TITLE
[ENHANCEMENT] Update vignette on README and links to more recent version

### ISSUE THREAD

**Issue by jackhump** [statOmics/satuRn#9]
Hi!  I wanted to go through the vignette carefully to see the example.
 I initially noticed that you use example data but don't provide a way of loading the example .RData objects into the environment, nor for creating the txInfo file.

Then I googled and found `https://rdrr.io/github/statOmics/satuRn/f/vignettes/Vignette.Rmd` which has all these things. 

To save future users the time, could you make sure the vignette and README on your github site is the latest version? I know keeping all this stuff in sync is annoying.

Looking forward to trying this out!

**Comment by jgilis** [comment]
Dear Jack,

My apologies for the inconvenience and thank you for getting back to us. 

It is true that the description provided in the `README` is not complete. My idea was to use the `README` as a quick demonstration of the different functionalities of `satuRn` but to refer to the actual `vignette` for a more detailed workflow. I now see how this can be quite confusing for end-users. I will make this explicit in the `README` soon.

For your information, the vignette is also available from our `pkgdwn` website https://statomics.github.io/satuRn/. In addition, `satuRn` will be available from `Bioconductor` in the next release, which should take place at the end of April.

If there are any other issues - or if you have questions/remarks/suggestions - do not hesitate to contact me!

Kind regards

**Comment by jackhump** [comment]
I see, thanks! I would still suggest that if you include test data then having a ready-made txInfo for your test set would be handy for first-time users, and would make the brief example in the README able to just be copied into the R console to try out.

I'll leave issue open for now but feel free to close.

**Comment by jgilis** [comment]
Added reference to the vignette in the description.
